name: docx_template
description: A Docx template engine.
version: 0.1.1
author: Pavel Snitko <brian57reg@gmail.com>
homepage: https://github.com/PavelS0/docx_template_dart
environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  archive: ^2.0.11
  xml: ^3.5.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
